from types import SimpleNamespace
import json
from io import BytesIO
import pytest
from PIL import Image


def service():
    from app import portrait_service
    return portrait_service


def config():
    return service().PortraitConfig(access_key='test-access-key', secret_key='test-secret-key')


def asset(**changes):
    item = {'Id':'asset-example','Name':'肖像','GroupId':'group-example','ProjectName':'default','Status':'Active','AssetType':'Image','URL':'https://ark-asset.cn-beijing.volcengine.com/face.png?secret=hidden'}
    item.update(changes)
    return item


def group(**changes):
    item={'Id':'group-example','ProjectName':'default','GroupType':'LivenessFace'}
    item.update(changes)
    return item


def test_configuration_is_explicit_private_atomic_and_preserves_blank_secrets(tmp_path, monkeypatch):
    s=service(); settings=SimpleNamespace(storage_dir=tmp_path)
    from app import storage_settings
    monkeypatch.setattr(storage_settings,'load_config',lambda _:SimpleNamespace(access_key='tos-ak',secret_key='tos-sk'))
    assert not s.load_config(settings).ready
    s.save_config(settings,{'access_key':'test-access-key','secret_key':'test-secret-key'})
    saved=s.save_config(settings,{'access_key':'','secret_key':'','project_name':'production'})
    assert saved.secret_key=='test-secret-key'
    public=s.public_config(settings)
    assert public['has_credentials'] and public['ready']
    assert 'test-secret-key' not in json.dumps(public) and 'access_key' not in public
    assert 'test-secret-key' not in repr(saved)
    assert json.loads((tmp_path/'private'/'portrait.json').read_text())['project_name']=='production'
    assert not list((tmp_path/'private').glob('*.tmp'))
    old=s.fingerprint(saved)
    assert s.fingerprint(s.save_config(settings,{'project_name':'default'}))!=old
    using=s.save_config(settings,{'use_storage_credentials':True})
    assert using.access_key=='tos-ak'
    raw=json.loads((tmp_path/'private'/'portrait.json').read_text())
    assert raw['access_key']=='test-access-key'
    assert not s.save_config(settings,{'clear_credentials':True}).ready
    assert not s.load_config(settings).use_storage_credentials


@pytest.mark.parametrize('payload',[{'unknown':1},{'use_storage_credentials':'true'},{'project_name':''},{'access_key':None},{'clear_credentials':'yes'},{'secret_key':'key\nleak'}])
def test_configuration_rejects_invalid_values(tmp_path,payload):
    with pytest.raises(ValueError): service().save_config(SimpleNamespace(storage_dir=tmp_path),payload)


def test_changed_access_key_does_not_reuse_old_secret(tmp_path):
    s=service(); settings=SimpleNamespace(storage_dir=tmp_path)
    s.save_config(settings,{'access_key':'one','secret_key':'secret'})
    assert not s.save_config(settings,{'access_key':'two'}).ready


def test_official_sdk_signing_vector():
    # Fixture generated by official volcengine/volc-sdk-python SignerV4.py,
    # MetaData.py and Util.py at main on 2026-09-27, with dummy AK/SK only.
    headers=service().signed_headers(config(),'ListAssets',b'{"ProjectName":"default"}','20260927T010203Z')
    assert headers['X-Content-Sha256']=='7e0a39e645f91c0fa13aea4108715f9f85a3f55f8d3e6af22c41b5b9d11fbde3'
    assert headers['Authorization']=='HMAC-SHA256 Credential=test-access-key/20260927/cn-beijing/ark/request, SignedHeaders=content-type;host;x-content-sha256;x-date, Signature=6201838d12a76606a4405385148edbc57a9c6bb659a09c7eed799afda6fbec87'


def test_get_asset_validates_group_and_project(monkeypatch):
    s=service(); client=s.ArkPortraitClient(config()); calls=[]
    def request(action,payload):
        calls.append((action,payload)); return asset() if action=='GetAsset' else group()
    monkeypatch.setattr(client,'_request',request)
    value=client.get_asset('asset-example')
    assert value['remote_asset_id']=='asset-example' and value['project']=='default'
    assert calls==[('GetAsset',{'Id':'asset-example','ProjectName':'default'}),('GetAssetGroup',{'Id':'group-example','ProjectName':'default'})]


@pytest.mark.parametrize('bad_asset,bad_group',[
    ({'Status':'Processing'},{}),({'AssetType':'Video'},{}),({'ProjectName':'other'},{}),({'Id':'asset-other'},{}),
    ({'GroupId':'file:///local'},{}),({}, {'GroupType':'AIGC'}),({}, {'ProjectName':'other'}),({}, {'Id':'group-other'}),
])
def test_unauthorized_asset_is_rejected(monkeypatch,bad_asset,bad_group):
    s=service(); client=s.ArkPortraitClient(config())
    monkeypatch.setattr(client,'_request',lambda action,payload:asset(**bad_asset) if action=='GetAsset' else group(**bad_group))
    with pytest.raises(s.PortraitError): client.get_asset('asset-example')


def test_list_paginates_filters_and_hides_nonimages(monkeypatch):
    s=service(); client=s.ArkPortraitClient(config()); calls=[]
    def request(action,payload):
        calls.append(payload)
        return {'Items':[asset(),asset(Id='asset-video',AssetType='Video')],'NextToken':'page2'} if 'NextToken' not in payload else {'Items':[asset(Id='asset-second')]}
    monkeypatch.setattr(client,'_request',request)
    assert [x['remote_asset_id'] for x in client.list_assets()]==['asset-example','asset-second']
    assert calls[0]['Filter']=={'GroupType':'LivenessFace','Statuses':['Active']}
    assert calls[1]['NextToken']=='page2'
    assert calls[1]['ProjectName']=='default'


def test_pagination_repeated_token_fails_safely(monkeypatch):
    s=service(); client=s.ArkPortraitClient(config())
    monkeypatch.setattr(client,'_request',lambda *args:{'Items':[],'NextToken':'repeat'})
    with pytest.raises(s.PortraitError): client.list_assets()


def test_http_errors_never_echo_remote_details(monkeypatch):
    s=service(); client=s.ArkPortraitClient(config()); captured={}
    class Response:
        status_code=200
        def json(self): return {'ResponseMetadata':{'Error':{'Message':'test-secret-key https://private/?token=foo'}}}
        def close(self): pass
    def post(url,**kwargs): captured.update(url=url,**kwargs); return Response()
    monkeypatch.setattr(s.requests,'post',post)
    with pytest.raises(s.PortraitError) as exc: client.get_asset('asset-example')
    assert 'test-secret-key' not in str(exc.value) and 'token' not in str(exc.value)
    assert captured['url']=='https://ark.cn-beijing.volcengineapi.com/?Action=GetAsset&Version=2024-01-01'
    assert captured['allow_redirects'] is False


@pytest.mark.parametrize('url',['http://ark-asset.cn-beijing.volcengine.com/a.png','https://evil.example/a.png','https://ark-asset.cn-beijing.volcengine.com.evil.example/a.png','https://user@ark-asset.cn-beijing.volcengine.com/a.png','https://127.0.0.1/a.png'])
def test_download_rejects_untrusted_host_before_network(tmp_path,url):
    s=service()
    with pytest.raises(s.PortraitError): s.download_image({'url':url},tmp_path/'face.png')
    assert not (tmp_path/'face.png').exists()


@pytest.mark.parametrize('hostname',['ark-asset.cn-beijing.volcengine.com','ark-media-asset.tos-cn-beijing.volces.com'])
def test_download_pins_public_dns_validates_image_and_is_atomic(tmp_path,monkeypatch,hostname):
    s=service(); raw=BytesIO(); Image.new('RGB',(2,2)).save(raw,format='PNG'); data=raw.getvalue()
    monkeypatch.setattr(s.socket,'getaddrinfo',lambda *a,**k:[(2,1,6,'',('8.8.8.8',443))])
    captured={}
    class Response:
        status_code=200; headers={'Content-Type':'image/png'}
        def iter_content(self,n): yield data
        def close(self): pass
    def pinned(url,addresses,headers): captured['addresses']=addresses; return Response()
    from app import tikhub
    monkeypatch.setattr(tikhub,'_get_pinned_video',pinned)
    destination=tmp_path/'face.png'
    assert s.download_image({'url':'https://'+hostname+'/verified.png'},destination)==destination
    assert destination.read_bytes()==data and captured['addresses']==('8.8.8.8',)


def test_download_rejects_private_dns(tmp_path,monkeypatch):
    s=service(); monkeypatch.setattr(s.socket,'getaddrinfo',lambda *a,**k:[(2,1,6,'',('127.0.0.1',443))])
    with pytest.raises(s.PortraitError): s.download_image({'url':asset()['URL']},tmp_path/'face.png')


def test_list_filters_wrong_project_and_stops_at_total_bound(monkeypatch):
    s=service(); client=s.ArkPortraitClient(config()); count=0
    def request(*args):
        nonlocal count
        count+=1
        return {'Items':[asset(ProjectName='other') for _ in range(100)],'NextToken':str(count)}
    monkeypatch.setattr(client,'_request',request)
    with pytest.raises(s.PortraitError): client.list_assets()
    assert count==11


@pytest.mark.parametrize('status,headers,data',[
    (302,{'Location':'https://127.0.0.1/private'},b''),
    (200,{'Content-Length':str(21*1024*1024)},b''),
    (200,{},b'not an image'),
    (200,{},b'<svg onload="alert(1)"></svg>'),
])
def test_download_failures_keep_existing_destination_and_remove_temporary(tmp_path,monkeypatch,status,headers,data):
    s=service(); monkeypatch.setattr(s.socket,'getaddrinfo',lambda *a,**k:[(2,1,6,'',('8.8.8.8',443))])
    class Response:
        status_code=status
        def __init__(self): self.headers=headers
        def iter_content(self,n): yield data
        def close(self): pass
    from app import tikhub
    monkeypatch.setattr(tikhub,'_get_pinned_video',lambda *a:Response())
    destination=tmp_path/'face.png'; destination.write_bytes(b'existing')
    with pytest.raises(s.PortraitError): s.download_image({'url':asset()['URL']},destination)
    assert destination.read_bytes()==b'existing'
    assert not list(tmp_path.glob('*.tmp'))


def test_signing_serialized_utf8_body_matches_sent_content(monkeypatch):
    import hashlib
    s=service(); client=s.ArkPortraitClient(config())
    class Response:
        status_code=200
        def json(self): return {'Result':{'Items':[]}}
        def close(self): pass
    def post(url,**kwargs):
        assert kwargs['headers']['X-Content-Sha256']==hashlib.sha256(kwargs['data']).hexdigest()
        assert json.loads(kwargs['data'])['ProjectName']=='中文项目'
        return Response()
    monkeypatch.setattr(s.requests,'post',post)
    assert client._request('ListAssets',{'ProjectName':'中文项目'})=={'Items':[]}
